version: '3'
services:

  app_frontend:
    container_name: app_frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 80:80
  app:
    container_name: app_backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    environment:
      - PORT=8080
      - POSTGRES_DB_HOST=db
      - POSTGRES_DB_PORT=5432
      - POSTGRES_DB_USER=postgres
      - POSTGRES_DB_PASSWORD=password
      - POSTGRES_DB_NAME=users
    depends_on:
      - db
  db:
    image: postgres:alpine
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users

  migrate:
    image: migrate/migrate
    container_name: db_migration
    restart: on-failure
    volumes:
      - ./backend/migrations/sql:/database
    command:
      [
        "-path",
        "/database",
        "-verbose",
        "-database",
        "postgres://postgres:password@db:5432/users?sslmode=disable",
        "up"
      ]
    links:
      - db
    depends_on:
      - db

volumes:
  api:
  postgres-db:
